Fix a grammatical error (#4)
Fix a grammatical error in line 73 "await app.sendGroupMessage(group, MessageChain.creat([" which causes "AttributeError: type object 'MessageChain' has no attribute 'creat'" error.